module.exports = {
  cerSidebar: [
    'README',
    'HOME',
    'MASTER_OUTLINE',
    'ROADMAP',
    'CHANGELOG',
    'OBSIDIAN',
    {
      type: 'category',
      label: '00 Specification Framework',
      link: { type: 'doc', id: '00_Specification_Framework/README' },
      items: [{ type: 'autogenerated', dirName: '00_Specification_Framework' }]
    },
    {
      type: 'category',
      label: '01 Foundations',
      link: { type: 'doc', id: '01_Foundations/README' },
      items: [{ type: 'autogenerated', dirName: '01_Foundations' }]
    },
    {
      type: 'category',
      label: '02 Case Architecture',
      link: { type: 'doc', id: '02_Case_Architecture/README' },
      items: [{ type: 'autogenerated', dirName: '02_Case_Architecture' }]
    },
    {
      type: 'category',
      label: '03 Evidence System',
      link: { type: 'doc', id: '03_Evidence_System/README' },
      items: [{ type: 'autogenerated', dirName: '03_Evidence_System' }]
    },
    {
      type: 'category',
      label: '04 Document System',
      link: { type: 'doc', id: '04_Document_System/README' },
      items: [{ type: 'autogenerated', dirName: '04_Document_System' }]
    },
    {
      type: 'category',
      label: '05 Document Types',
      link: { type: 'doc', id: '05_Document_Types/README' },
      items: [{ type: 'autogenerated', dirName: '05_Document_Types' }]
    },
    {
      type: 'category',
      label: '06 Discovery System',
      link: { type: 'doc', id: '06_Discovery_System/README' },
      items: [{ type: 'autogenerated', dirName: '06_Discovery_System' }]
    },
    {
      type: 'category',
      label: '07 Information Economy',
      link: { type: 'doc', id: '07_Information_Economy/README' },
      items: [{ type: 'autogenerated', dirName: '07_Information_Economy' }]
    },
    {
      type: 'category',
      label: '08 Failure Modes',
      link: { type: 'doc', id: '08_Failure_Modes/README' },
      items: [{ type: 'autogenerated', dirName: '08_Failure_Modes' }]
    },
    {
      type: 'category',
      label: '09 Validation',
      link: { type: 'doc', id: '09_Validation/README' },
      items: [{ type: 'autogenerated', dirName: '09_Validation' }]
    },
    {
      type: 'category',
      label: '10 Rendering',
      link: { type: 'doc', id: '10_Rendering/README' },
      items: [{ type: 'autogenerated', dirName: '10_Rendering' }]
    },
    {
      type: 'category',
      label: '11 Artifact Production',
      link: { type: 'doc', id: '11_Artifact_Production/README' },
      items: [{ type: 'autogenerated', dirName: '11_Artifact_Production' }]
    },
    {
      type: 'category',
      label: '12 Case Engine',
      link: { type: 'doc', id: '12_Case_Engine/README' },
      items: [{ type: 'autogenerated', dirName: '12_Case_Engine' }]
    },
    {
      type: 'category',
      label: '13 Production Graphs',
      link: { type: 'doc', id: '13_Production_Graphs/README' },
      items: [{ type: 'autogenerated', dirName: '13_Production_Graphs' }]
    },
    {
      type: 'category',
      label: '14 Compliance',
      link: { type: 'doc', id: '14_Compliance/README' },
      items: [{ type: 'autogenerated', dirName: '14_Compliance' }]
    },
    {
      type: 'category',
      label: '15 V1 Hardening',
      link: { type: 'doc', id: '15_V1_Hardening/README' },
      items: [{ type: 'autogenerated', dirName: '15_V1_Hardening' }]
    },
    { type: 'category', label: 'ADR', items: [{ type: 'autogenerated', dirName: 'adr' }] },
    { type: 'category', label: 'Rules', items: [{ type: 'autogenerated', dirName: 'rules' }] },
    { type: 'category', label: 'Patterns', items: [{ type: 'autogenerated', dirName: 'patterns' }] },
    { type: 'category', label: 'Schemas', items: [{ type: 'autogenerated', dirName: 'schemas' }] },
    { type: 'category', label: 'Tests', items: [{ type: 'autogenerated', dirName: 'tests' }] },
    { type: 'category', label: 'Extensions', items: [{ type: 'autogenerated', dirName: 'extensions' }] }
  ]
};
